# React App - goupdate configuration
# Demonstrates: groups, incremental updates, ignoring types, system tests

extends: [default]

rules:
  npm:
    groups:
      framework:
        - react
        - react-dom
        - react-router-dom
      state:
        - "@tanstack/react-query"
        - zustand
      dev:
        - typescript
        - vite
        - vitest

    # Update React incrementally (nearest version instead of latest)
    incremental:
      - react
      - react-dom

    # Skip type packages
    ignore:
      - "@types/*"

    # Note: Pre-release filtering inherits from default config
    # Default patterns exclude: alpha, beta, rc, canary, dev, snapshot, nightly, preview

# System tests validate app health before and after updates
system_tests:
  run_preflight: true
  run_mode: after_each
  stop_on_fail: true
  tests:
    # Quick type check and lint
    - name: type-check
      commands: npm run type-check
      timeout_seconds: 60
      continue_on_fail: true  # Lint issues don't block updates

    # Unit tests with Vitest
    - name: unit-tests
      commands: npm test -- --run
      timeout_seconds: 120

    # Build verification
    - name: build
      commands: npm run build
      timeout_seconds: 300

    # Start preview server and verify HTTP 200 response
    - name: http-test
      commands: |
        npm run preview -- --port 4173 &
        SERVER_PID=$!
        sleep 3
        # Check HTTP 200 status and response content
        STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:4173/)
        BODY=$(curl -s http://localhost:4173/)
        kill $SERVER_PID 2>/dev/null || pkill -f "vite preview" || true
        # Verify status is 2xx and response contains expected content
        [ "$STATUS" -ge 200 ] && [ "$STATUS" -lt 300 ] || { echo "HTTP status $STATUS != 2xx"; exit 1; }
        echo "$BODY" | grep -q "React Dashboard" || { echo "Response missing expected content"; exit 1; }
        echo "HTTP test passed! Status: $STATUS"
      timeout_seconds: 60
