# Go CLI - goupdate configuration
# Demonstrates: groups for Go modules, system tests with CLI verification

extends: [default]

rules:
  mod:
    groups:
      cli:
        - github.com/spf13/cobra
        - github.com/spf13/viper
      logging:
        - go.uber.org/zap

# System tests for Go CLI projects
system_tests:
  run_preflight: true
  run_mode: after_each
  stop_on_fail: true
  tests:
    # Build the binary
    - name: build
      commands: go build -o myapp .
      timeout_seconds: 120

    # Verify CLI runs and responds correctly
    - name: cli-test
      commands: |
        # Test default command
        RESPONSE=$(./myapp)
        echo "Default response: $RESPONSE"

        # Test ping subcommand
        PING=$(./myapp ping)
        echo "Ping response: $PING"

        # Verify responses
        echo "$RESPONSE" | grep -q "Hello" || { echo "ERROR: Default command failed"; exit 1; }
        echo "$PING" | grep -q "pong" || { echo "ERROR: Ping command failed"; exit 1; }
        echo "CLI tests passed!"
      timeout_seconds: 30
