# Frontend App - goupdate configuration
# Example: pnpm-based Vue.js frontend with grouped dependencies
#
# Based on matematikk-mooc/frontend project structure

extends: [default]

rules:
  pnpm:
    # Only group packages with actual version coupling (peer dependencies)
    groups:
      # Vue core - vuex/vue-router have peer deps on vue
      vue:
        - vue
        - vuex
        - vue-router

      # React - must have matching versions
      react:
        - react
        - react-dom

      # Webpack core - cli/dev-server depend on webpack
      webpack:
        - webpack
        - webpack-cli
        - webpack-dev-server

      # Babel - loader depends on core
      babel:
        - babel-loader
        - "@babel/core"
        - "@babel/preset-env"

      # Playwright - test package depends on playwright
      playwright:
        - playwright
        - "@playwright/test"

# System tests to verify build after updates
# Note: This is a config-only example - copy to your actual Vue/pnpm project
system_tests:
  run_preflight: true
  run_mode: after_each
  stop_on_fail: true
  tests:
    - name: build
      commands: |
        pnpm install
        pnpm run build
      timeout_seconds: 300

    # Start preview server and verify HTTP response (uncomment when using with actual project)
    # - name: http-test
    #   commands: |
    #     # Start preview server in background
    #     pnpm run preview -- --port 4174 &
    #     SERVER_PID=$!
    #     sleep 3
    #     # Verify server responds
    #     STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:4174/)
    #     kill $SERVER_PID 2>/dev/null || true
    #     [ "$STATUS" -ge 200 ] && [ "$STATUS" -lt 400 ] || exit 1
    #   timeout_seconds: 60
