# Frontend App - goupdate configuration
# Example: pnpm-based Vue.js frontend with grouped dependencies
#
# Based on matematikk-mooc/frontend project structure

extends: [default]

rules:
  pnpm:
    # Only group packages with actual version coupling (peer dependencies)
    groups:
      # Vue core - vuex/vue-router have peer deps on vue
      vue:
        - vue
        - vuex
        - vue-router

      # React - must have matching versions
      react:
        - react
        - react-dom

      # Webpack core - cli/dev-server depend on webpack
      webpack:
        - webpack
        - webpack-cli
        - webpack-dev-server

      # Babel - loader depends on core
      babel:
        - babel-loader
        - "@babel/core"
        - "@babel/preset-env"

      # Playwright - test package depends on playwright
      playwright:
        - playwright
        - "@playwright/test"

    # Override lock_files for offline testing (when pnpm not installed)
    # This uses regex extraction instead of pnpm ls --json command
    lock_files:
      - files: ["**/pnpm-lock.yaml"]
        format: raw
        extraction:
          # Parse pnpm-lock.yaml v9 importers format:
          # Both quoted and unquoted package names:
          #   '@babel/core':
          #     specifier: ^7.26.9
          #     version: 7.26.9
          #   lodash:
          #     specifier: ^4.17.21
          #     version: 4.17.21
          # Also handles complex versions like 7.26.9(@babel/core@7.26.9) by stopping at (
          pattern: '(?m)^\s{6}''?(?P<n>[@\w\-\.\/]+)''?:\s*\n\s+specifier:[^\n]+\n\s+version:\s*(?P<version>[\d\.]+)'

# System test to verify no compile errors after updates
system_tests:
  run_preflight: true
  run_mode: after_each
  stop_on_fail: true
  tests:
    - name: build
      commands: |
        pnpm install
        pnpm run build
      timeout_seconds: 300
