# Frontend App - goupdate configuration
# Example: pnpm-based Vue.js frontend with grouped dependencies
#
# Based on matematikk-mooc/frontend project structure

extends: [default]

rules:
  pnpm:
    # Group related packages for coordinated updates
    groups:
      # Vue ecosystem - update together
      vue:
        - vue
        - vuex
        - vue-router
        - "@vue/reactivity"
        - "@vueuse/core"

      # React (used alongside Vue in this project)
      react:
        - react
        - react-dom

      # Build tooling
      build:
        - webpack
        - webpack-cli
        - webpack-dev-server
        - vue-loader
        - sass
        - sass-loader
        - babel-loader
        - "@babel/core"
        - "@babel/preset-env"

      # Testing tools
      testing:
        - playwright
        - "@playwright/test"

      # Linting
      lint:
        - eslint
        - eslint-plugin-vue
        - prettier

      # RxJS
      rxjs:
        - rxjs

    # Note: Pre-release filtering inherits from default config
    # Default patterns exclude: alpha, beta, rc, canary, dev, snapshot, nightly, preview, next

# System test to verify no compile errors after updates
system_tests:
  run_preflight: true
  run_mode: after_each
  stop_on_fail: true
  tests:
    - name: build
      commands: |
        pnpm install
        pnpm run build
      timeout_seconds: 300
