# Example Ruby API with version diversity for testing major/minor/patch updates
# Uses pessimistic version constraints (~>) common in Ruby projects

source 'https://rubygems.org'

ruby '3.2.0'

gem 'rails', '~> 7.0.4'
gem 'puma', '~> 6.0'
gem 'pg', '~> 1.4'
gem 'redis', '~> 5.0'
gem 'sidekiq', '~> 7.0'
gem 'jwt', '~> 2.7'
gem 'rack-cors', '~> 2.0'
gem 'oj', '~> 3.14'

group :development, :test do
  gem 'rspec-rails', '~> 6.0'
  gem 'factory_bot_rails', '~> 6.2'
  gem 'faker', '~> 3.1'
end

group :development do
  gem 'rubocop', '~> 1.50'
  gem 'rubocop-rails', '~> 2.19'
end
