# Django App - goupdate configuration
# Demonstrates: groups for Python, excluding dev tools, system tests

extends: [default]

rules:
  requirements:
    groups:
      web:
        - Django
        - djangorestframework
        - gunicorn
      async:
        - celery
        - redis
      database:
        - psycopg2-binary
      testing:
        - pytest
        - pytest-django

    # Don't auto-update formatters
    ignore:
      - black
      - isort

    exclude_versions:
      - "(?i)dev"
      - "(?i)post"

# System tests for Django projects
system_tests:
  run_preflight: true
  run_mode: after_each
  stop_on_fail: true
  tests:
    # Run Django's system checks
    - name: django-check
      commands: python manage.py check
      timeout_seconds: 60

    # Run pytest with Django plugin
    - name: unit-tests
      commands: pytest -v --tb=short
      timeout_seconds: 300
      env:
        DJANGO_SETTINGS_MODULE: "myapp.settings"
      continue_on_fail: true  # Skip if pytest not installed

    # Start server and verify HTTP 200 response
    - name: http-test
      commands: |
        python manage.py runserver 0.0.0.0:8765 &
        SERVER_PID=$!
        sleep 3
        # Check HTTP 200 status and response content
        STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8765/health/)
        BODY=$(curl -s http://localhost:8765/health/)
        kill $SERVER_PID 2>/dev/null || true
        # Verify status is 2xx and response contains expected content
        [ "$STATUS" -ge 200 ] && [ "$STATUS" -lt 300 ] || { echo "HTTP status $STATUS != 2xx"; exit 1; }
        echo "$BODY" | grep -q '"status"' || { echo "Response missing status field"; exit 1; }
        echo "HTTP test passed! Status: $STATUS"
      timeout_seconds: 60
      env:
        DJANGO_SETTINGS_MODULE: "myapp.settings"
