# Laravel App - goupdate configuration
# Demonstrates: groups for PHP/Composer, system tests with HTTP verification

extends: [default]

rules:
  composer:
    # Only group packages with actual version coupling
    groups:
      # Laravel core - sanctum has peer dep on framework
      # Use with_all_dependencies for complex transitive dependencies
      laravel:
        with_all_dependencies: true
        packages:
          - laravel/framework
          - laravel/sanctum

    # Note: Pre-release filtering inherits from default config
    # Default patterns exclude: alpha, beta, rc, dev, canary, snapshot, nightly, preview, next

# System tests for Laravel projects
system_tests:
  run_preflight: true
  run_mode: after_each
  stop_on_fail: true
  tests:
    # Install dependencies
    - name: composer-install
      commands: composer install --no-interaction --prefer-dist
      timeout_seconds: 300
      continue_on_fail: true  # Skip if composer not available

    # Start server and verify HTTP 200 response
    - name: http-test
      commands: |
        php artisan serve --port=8765 &
        SERVER_PID=$!
        sleep 3
        # Check HTTP 200 status and response content
        STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8765/api/health)
        BODY=$(curl -s http://localhost:8765/api/health)
        kill $SERVER_PID 2>/dev/null || true
        # Verify status is 2xx and response contains expected content
        [ "$STATUS" -ge 200 ] && [ "$STATUS" -lt 300 ] || { echo "HTTP status $STATUS != 2xx"; exit 1; }
        echo "$BODY" | grep -q '"status"' || { echo "Response missing status field"; exit 1; }
        echo "HTTP test passed! Status: $STATUS"
      timeout_seconds: 60
