# Laravel App - goupdate configuration
# Demonstrates: groups for PHP/Composer

extends: [default]

rules:
  composer:
    # Only group packages with actual version coupling
    groups:
      # Laravel core - sanctum has peer dep on framework
      laravel:
        - laravel/framework
        - laravel/sanctum

    # Note: Pre-release filtering inherits from default config
    # Default patterns exclude: alpha, beta, rc, dev, canary, snapshot, nightly, preview, next
