# Laravel App - goupdate configuration
# Demonstrates: groups for PHP/Composer

extends: [default]

rules:
  composer:
    groups:
      framework:
        - laravel/framework
        - laravel/sanctum
      plugins:
        - spatie/laravel-permission
        - predis/predis
      dev:
        - phpunit/phpunit
        - laravel/pint
        - nunomaduro/larastan

    # Note: Pre-release filtering inherits from default config
    # Default patterns exclude: alpha, beta, rc, dev, canary, snapshot, nightly, preview, next
